source "http://rubygems.org"

gemspec

gem 'kartit', :path => '../'

gem 'pry'
gem 'pry-debugger'

group :test do
  gem 'minitest', '4.7.4'
  gem 'minitest-spec-context'
  gem 'simplecov'
  gem 'activesupport'
  gem 'mocha'
end
