source "http://rubygems.org"

gemspec

gem 'kartit', :path => '.'
gem 'kartit_foreman', :path => '../kartit-foreman'
gem 'kartit_katello', :path => '../kartit-katello'

gem 'pry'
gem 'pry-debugger'

group :test do
  gem 'minitest', '4.7.4'
  gem 'minitest-spec-context'
  gem 'simplecov'
  gem 'mocha'
end
